function data = load_rocksim(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as column vectors.
%   [TIME1,THRUSTN,XTHRUSTN,YTHRUSTN,ACCELERATIONFEETSECSEC,XACCELERATIONFEETSECSEC,YACCELERATIONFEETSECSEC,ACCELERATIONTOTALFEETSECS,XACCELERATIONTOTALFEETSEC,YACCELERATIONTOTALFEETSEC,VELOCITYFEETSEC,XVELOCITYFEETSEC,YVELOCITYFEETSEC,MACHNUMBER,ALTITUDEFEET,RANGEFEET,CD1,DRAGFORCEN,XDRAGFORCEN,YDRAGFORCEN,LONGITUDINALMOMENTOFINERT,RADIALMOMENTOFINERTIAOUNC,FLIGHTANGLEDEG,GAMMAVELOCITYTANGENTANGLE,WINDANGLEOFATTACKDEG,CGINCHES,MASSOUNCES,CPINCHES,CNANORMALFORCECOEFFICIENT,STATICSTABILITYMARGINCALI,ANGULARACCELERATIONRADSS,TORQUENM,PITCHRATERADS,PITCHFORCEN,XWINDVELOCITYMILESHOUR,CROSSWINDDRAGN,CROSSWINDLIFTN,XWINDINDUCEDACCELERATIONF,YWINDINDUCEDLIFTFEETSECSE,XWINDDRIFTVELOCITYFEETSEC,YWINDDRIFTVELOCITYFEETSEC,THERMALRISEVELOCITYMILESH,GRAVITYFEETSECSEC,PRESSUREKPA,TEMPERATUREDEGREESFAHRENH,DENSITYKGM3,VISCOSITY,KINEMATICVISCOSITY,SOUNDVELOCITYFEETSEC,CORRECTIVEMOMENTCOEFFICIE,DAMPINGMOMENTCOEFFICIENT,NATFREQATZEROROLLRATERADS,DAMPINGRATIO,PRECFREQRADS,NATCOUPLEDFREQUENCYRADS,COUPLEDDAMPINGRATIO,BOOSTER2VELOCITYFEETSEC,BOOSTER2XVELOCITYFEETSEC,BOOSTER2YVELOCITYFEETSEC,BOOSTER2RANGEFEET,BOOSTER2ALTITUDEFEET,BOOSTER2FLIGHTANGLEDEG,BOOSTER1VELOCITYFEETSEC,BOOSTER1XVELOCITYFEETSEC,BOOSTER1YVELOCITYFEETSEC,BOOSTER1RANGEFEET,BOOSTER1ALTITUDEFEET,BOOSTER1FLIGHTANGLE]
%   = IMPORTFILE(FILENAME) Reads data from text file FILENAME for the
%   default selection.
%
%   [TIME1,THRUSTN,XTHRUSTN,YTHRUSTN,ACCELERATIONFEETSECSEC,XACCELERATIONFEETSECSEC,YACCELERATIONFEETSECSEC,ACCELERATIONTOTALFEETSECS,XACCELERATIONTOTALFEETSEC,YACCELERATIONTOTALFEETSEC,VELOCITYFEETSEC,XVELOCITYFEETSEC,YVELOCITYFEETSEC,MACHNUMBER,ALTITUDEFEET,RANGEFEET,CD1,DRAGFORCEN,XDRAGFORCEN,YDRAGFORCEN,LONGITUDINALMOMENTOFINERT,RADIALMOMENTOFINERTIAOUNC,FLIGHTANGLEDEG,GAMMAVELOCITYTANGENTANGLE,WINDANGLEOFATTACKDEG,CGINCHES,MASSOUNCES,CPINCHES,CNANORMALFORCECOEFFICIENT,STATICSTABILITYMARGINCALI,ANGULARACCELERATIONRADSS,TORQUENM,PITCHRATERADS,PITCHFORCEN,XWINDVELOCITYMILESHOUR,CROSSWINDDRAGN,CROSSWINDLIFTN,XWINDINDUCEDACCELERATIONF,YWINDINDUCEDLIFTFEETSECSE,XWINDDRIFTVELOCITYFEETSEC,YWINDDRIFTVELOCITYFEETSEC,THERMALRISEVELOCITYMILESH,GRAVITYFEETSECSEC,PRESSUREKPA,TEMPERATUREDEGREESFAHRENH,DENSITYKGM3,VISCOSITY,KINEMATICVISCOSITY,SOUNDVELOCITYFEETSEC,CORRECTIVEMOMENTCOEFFICIE,DAMPINGMOMENTCOEFFICIENT,NATFREQATZEROROLLRATERADS,DAMPINGRATIO,PRECFREQRADS,NATCOUPLEDFREQUENCYRADS,COUPLEDDAMPINGRATIO,BOOSTER2VELOCITYFEETSEC,BOOSTER2XVELOCITYFEETSEC,BOOSTER2YVELOCITYFEETSEC,BOOSTER2RANGEFEET,BOOSTER2ALTITUDEFEET,BOOSTER2FLIGHTANGLEDEG,BOOSTER1VELOCITYFEETSEC,BOOSTER1XVELOCITYFEETSEC,BOOSTER1YVELOCITYFEETSEC,BOOSTER1RANGEFEET,BOOSTER1ALTITUDEFEET,BOOSTER1FLIGHTANGLE]
%   = IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data from rows STARTROW
%   through ENDROW of text file FILENAME.
%
% Example:
%   [Time1,ThrustN,xThrustN,yThrustN,AccelerationFeetsecsec,xAccelerationFeetsecsec,yAccelerationFeetsecsec,AccelerationTotalFeetsecs,xAccelerationTotalFeetsec,yAccelerationTotalFeetsec,VelocityFeetSec,xVelocityFeetSec,yVelocityFeetSec,Machnumber,AltitudeFeet,RangeFeet,Cd1,DragforceN,xDragforceN,yDragforceN,Longitudinalmomentofinert,RadialmomentofinertiaOunc,FlightangleDeg,GammaVelocitytangentangle,WindangleofattackDeg,CGInches,MassOunces,CPInches,CNanormalforcecoefficient,StaticstabilitymarginCali,AngularaccelerationRadss,TorqueNm,Pitchraterads,PitchforceN,xWindvelocityMilesHour,CrosswinddragN,CrosswindliftN,XWindinducedaccelerationF,YWindinducedliftFeetsecse,XWinddriftvelocityFeetSec,YWinddriftvelocityFeetSec,ThermalrisevelocityMilesH,GravityFeetsecsec,PressureKPa,TemperatureDegreesFahrenh,Densitykgm3,Viscosity,Kinematicviscosity,SoundvelocityFeetSec,Correctivemomentcoefficie,Dampingmomentcoefficient,NatFreqatzerorollraterads,DampingRatio,PrecFreqrads,NatCoupledFrequencyrads,CoupledDampingRatio,Booster2VelocityFeetSec,Booster2xVelocityFeetSec,Booster2yVelocityFeetSec,Booster2rangeFeet,Booster2altitudeFeet,Booster2flightangleDeg,Booster1VelocityFeetSec,Booster1xVelocityFeetSec,Booster1yVelocityFeetSec,Booster1rangeFeet,Booster1altitudeFeet,Booster1flightangle]
%   = importfile('30k.csv',2, 1993);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2014/02/24 22:00:19

%% Initialize variables.
delimiter = '\t';
if nargin<=2
    startRow = 2;
    endRow = inf;
end

%% Format string for each line of text:
%   column1: double (%f)
%	column2: double (%f)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
%	column8: double (%f)
%   column9: double (%f)
%	column10: double (%f)
%   column11: double (%f)
%	column12: double (%f)
%   column13: double (%f)
%	column14: double (%f)
%   column15: double (%f)
%	column16: double (%f)
%   column17: double (%f)
%	column18: double (%f)
%   column19: double (%f)
%	column20: double (%f)
%   column21: double (%f)
%	column22: double (%f)
%   column23: double (%f)
%	column24: double (%f)
%   column25: double (%f)
%	column26: double (%f)
%   column27: double (%f)
%	column28: double (%f)
%   column29: double (%f)
%	column30: double (%f)
%   column31: double (%f)
%	column32: double (%f)
%   column33: double (%f)
%	column34: double (%f)
%   column35: double (%f)
%	column36: double (%f)
%   column37: double (%f)
%	column38: double (%f)
%   column39: double (%f)
%	column40: double (%f)
%   column41: double (%f)
%	column42: double (%f)
%   column43: double (%f)
%	column44: double (%f)
%   column45: double (%f)
%	column46: double (%f)
%   column47: double (%f)
%	column48: double (%f)
%   column49: double (%f)
%	column50: double (%f)
%   column51: double (%f)
%	column52: double (%f)
%   column53: double (%f)
%	column54: double (%f)
%   column55: double (%f)
%	column56: double (%f)
%   column57: double (%f)
%	column58: double (%f)
%   column59: double (%f)
%	column60: double (%f)
%   column61: double (%f)
%	column62: double (%f)
%   column63: double (%f)
%	column64: double (%f)
%   column65: double (%f)
%	column66: double (%f)
%   column67: double (%f)
%	column68: double (%f)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
data = struct();
data.Time1 = dataArray{:, 1};
data.ThrustN = dataArray{:, 2};
data.xThrustN = dataArray{:, 3};
data.yThrustN = dataArray{:, 4};
data.AccelerationFeetsecsec = dataArray{:, 5};
data.xAccelerationFeetsecsec = dataArray{:, 6};
data.yAccelerationFeetsecsec = dataArray{:, 7};
data.AccelerationTotalFeetsecs = dataArray{:, 8};
data.xAccelerationTotalFeetsec = dataArray{:, 9};
data.yAccelerationTotalFeetsec = dataArray{:, 10};
data.VelocityFeetSec = dataArray{:, 11};
data.xVelocityFeetSec = dataArray{:, 12};
data.yVelocityFeetSec = dataArray{:, 13};
data.Machnumber = dataArray{:, 14};
data.AltitudeFeet = dataArray{:, 15};
data.RangeFeet = dataArray{:, 16};
data.Cd1 = dataArray{:, 17};
data.DragforceN = dataArray{:, 18};
data.xDragforceN = dataArray{:, 19};
data.yDragforceN = dataArray{:, 20};
data.Longitudinalmomentofinert = dataArray{:, 21};
data.RadialmomentofinertiaOunc = dataArray{:, 22};
data.FlightangleDeg = dataArray{:, 23};
data.GammaVelocitytangentangle = dataArray{:, 24};
data.WindangleofattackDeg = dataArray{:, 25};
data.CGInches = dataArray{:, 26};
data.MassOunces = dataArray{:, 27};
data.CPInches = dataArray{:, 28};
data.CNanormalforcecoefficient = dataArray{:, 29};
data.StaticstabilitymarginCali = dataArray{:, 30};
data.AngularaccelerationRadss = dataArray{:, 31};
data.TorqueNm = dataArray{:, 32};
data.Pitchraterads = dataArray{:, 33};
data.PitchforceN = dataArray{:, 34};
data.xWindvelocityMilesHour = dataArray{:, 35};
data.CrosswinddragN = dataArray{:, 36};
data.CrosswindliftN = dataArray{:, 37};
data.XWindinducedaccelerationF = dataArray{:, 38};
data.YWindinducedliftFeetsecse = dataArray{:, 39};
data.XWinddriftvelocityFeetSec = dataArray{:, 40};
data.YWinddriftvelocityFeetSec = dataArray{:, 41};
data.ThermalrisevelocityMilesH = dataArray{:, 42};
data.GravityFeetsecsec = dataArray{:, 43};
data.PressureKPa = dataArray{:, 44};
data.TemperatureDegreesFahrenh = dataArray{:, 45};
data.Densitykgm3 = dataArray{:, 46};
data.Viscosity = dataArray{:, 47};
data.Kinematicviscosity = dataArray{:, 48};
data.SoundvelocityFeetSec = dataArray{:, 49};
data.Correctivemomentcoefficie = dataArray{:, 50};
data.Dampingmomentcoefficient = dataArray{:, 51};
data.NatFreqatzerorollraterads = dataArray{:, 52};
data.DampingRatio = dataArray{:, 53};
data.PrecFreqrads = dataArray{:, 54};
data.NatCoupledFrequencyrads = dataArray{:, 55};
data.CoupledDampingRatio = dataArray{:, 56};
data.Booster2VelocityFeetSec = dataArray{:, 57};
data.Booster2xVelocityFeetSec = dataArray{:, 58};
data.Booster2yVelocityFeetSec = dataArray{:, 59};
data.Booster2rangeFeet = dataArray{:, 60};
data.Booster2altitudeFeet = dataArray{:, 61};
data.Booster2flightangleDeg = dataArray{:, 62};
data.Booster1VelocityFeetSec = dataArray{:, 63};
data.Booster1xVelocityFeetSec = dataArray{:, 64};
data.Booster1yVelocityFeetSec = dataArray{:, 65};
data.Booster1rangeFeet = dataArray{:, 66};
data.Booster1altitudeFeet = dataArray{:, 67};
data.Booster1flightangle = dataArray{:, 68};

