function data = load_wind(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as column vectors.
%   [LEV,PRES,HGHT,TEMP1,DEWP,RH,DD1,WETB,DIR,SPD,THETA,THEV,THEW,THEE,W] =
%   IMPORTFILE(FILENAME) Reads data from text file FILENAME for the default
%   selection.
%
%   [LEV,PRES,HGHT,TEMP1,DEWP,RH,DD1,WETB,DIR,SPD,THETA,THEV,THEW,THEE,W] =
%   IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data from rows STARTROW
%   through ENDROW of text file FILENAME.
%
% Example:
%   [LEV,PRES,HGHT,TEMP1,DEWP,RH,DD1,WETB,DIR,SPD,THETA,THEV,THEW,THEE,W] =
%   importfile('wind.csv',3, 85);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2014/04/30 20:48:07

%% Initialize variables.
delimiter = ',';
if nargin<=2
    startRow = 3;
    endRow = inf;
end

%% Read columns of data as strings:
% For more information, see the TEXTSCAN documentation.
formatSpec = '%s%s%s%s%s%s%s%s%s%s%s%s%s%s%s%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Convert the contents of columns containing numeric strings to numbers.
% Replace non-numeric strings with NaN.
raw = repmat({''},length(dataArray{1}),length(dataArray)-1);
for col=1:length(dataArray)-1
    raw(1:length(dataArray{col}),col) = dataArray{col};
end
numericData = NaN(size(dataArray{1},1),size(dataArray,2));

for col=[1,2,3,4,5,6,7,8,9,10,11,12,13,14,15]
    % Converts strings in the input cell array to numbers. Replaced non-numeric
    % strings with NaN.
    rawData = dataArray{col};
    for row=1:size(rawData, 1);
        % Create a regular expression to detect and remove non-numeric prefixes and
        % suffixes.
        regexstr = '(?<prefix>.*?)(?<numbers>([-]*(\d+[\,]*)+[\.]{0,1}\d*[eEdD]{0,1}[-+]*\d*[i]{0,1})|([-]*(\d+[\,]*)*[\.]{1,1}\d+[eEdD]{0,1}[-+]*\d*[i]{0,1}))(?<suffix>.*)';
        try
            result = regexp(rawData{row}, regexstr, 'names');
            numbers = result.numbers;
            
            % Detected commas in non-thousand locations.
            invalidThousandsSeparator = false;
            if any(numbers==',');
                thousandsRegExp = '^\d+?(\,\d{3})*\.{0,1}\d*$';
                if isempty(regexp(thousandsRegExp, ',', 'once'));
                    numbers = NaN;
                    invalidThousandsSeparator = true;
                end
            end
            % Convert numeric strings to numbers.
            if ~invalidThousandsSeparator;
                numbers = textscan(strrep(numbers, ',', ''), '%f');
                numericData(row, col) = numbers{1};
                raw{row, col} = numbers{1};
            end
        catch me
        end
    end
end


%% Replace non-numeric cells with NaN
R = cellfun(@(x) ~isnumeric(x) && ~islogical(x),raw); % Find non-numeric cells
raw(R) = {NaN}; % Replace non-numeric cells

%% Allocate imported array to column variable names
data.LEV = cell2mat(raw(:, 1));     %
data.PRES = cell2mat(raw(:, 2));    %mb
data.HGHT = cell2mat(raw(:, 3));    %m
data.TEMP1 = cell2mat(raw(:, 4));   %C
data.DEWP = cell2mat(raw(:, 5));    %C
data.RH = cell2mat(raw(:, 6));      %%
data.DD1 = cell2mat(raw(:, 7));     %C
data.WETB = cell2mat(raw(:, 8));    %C
data.DIR = cell2mat(raw(:, 9));     %deg
data.SPD = cell2mat(raw(:, 10));    %knt
data.THETA = cell2mat(raw(:, 11));  %K
data.THEV = cell2mat(raw(:, 12));   %K
data.THEW = cell2mat(raw(:, 13));   %K
data.THEE = cell2mat(raw(:, 14));   %K
data.W = cell2mat(raw(:, 15));      %g/kg

