function data = load_aprs(filename, startRow, endRow)
%IMPORTFILE Import numeric data from a text file as column vectors.
%   [TIME,LASTTIME,LAT,LNG,SPEED,COURSE,ALTITUDE,COMMENT] =
%   IMPORTFILE(FILENAME) Reads data from text file FILENAME for the default
%   selection.
%
%   [TIME,LASTTIME,LAT,LNG,SPEED,COURSE,ALTITUDE,COMMENT] =
%   IMPORTFILE(FILENAME, STARTROW, ENDROW) Reads data from rows STARTROW
%   through ENDROW of text file FILENAME.
%
% Example:
%   [time,lasttime,lat,lng,speed,course,altitude,comment] =
%   importfile('aprs.csv',2, 37);
%
%    See also TEXTSCAN.

% Auto-generated by MATLAB on 2014/04/07 17:00:14

%% Initialize variables.
delimiter = ',';
if nargin<=2
    startRow = 2;
    endRow = inf;
end

%% Format string for each line of text:
%   column1: text (%s)
%	column2: text (%s)
%   column3: double (%f)
%	column4: double (%f)
%   column5: double (%f)
%	column6: double (%f)
%   column7: double (%f)
%	column8: text (%s)
% For more information, see the TEXTSCAN documentation.
formatSpec = '%s%s%f%f%f%f%f%s%f%f%[^\n\r]';

%% Open the text file.
fileID = fopen(filename,'r');

%% Read columns of data according to format string.
% This call is based on the structure of the file used to generate this
% code. If an error occurs for a different file, try regenerating the code
% from the Import Tool.
dataArray = textscan(fileID, formatSpec, endRow(1)-startRow(1)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(1)-1, 'ReturnOnError', false);
for block=2:length(startRow)
    frewind(fileID);
    dataArrayBlock = textscan(fileID, formatSpec, endRow(block)-startRow(block)+1, 'Delimiter', delimiter, 'HeaderLines', startRow(block)-1, 'ReturnOnError', false);
    for col=1:length(dataArray)
        dataArray{col} = [dataArray{col};dataArrayBlock{col}];
    end
end

%% Close the text file.
fclose(fileID);

%% Post processing for unimportable data.
% No unimportable data rules were applied during the import, so no post
% processing code is included. To generate code which works for
% unimportable data, select unimportable cells in a file and regenerate the
% script.

%% Allocate imported array to column variable names
data.time = dataArray{:, 1};               %date
data.lasttime = dataArray{:, 2};           %date  
data.lat = dataArray{:, 3};                %latitude
data.lng = dataArray{:, 4};                %longitude
data.speed = dataArray{:, 5};              %km/h
data.course = dataArray{:, 6};             %degrees where north = 0, east = 90
data.altitude = dataArray{:, 7};           %m
data.comment = dataArray{:, 8};            %device used
data.unix_time = dataArray{:, 9};          %seconds
data.unix_lasttime = dataArray{:, 10};     %seconds


